spring:
  profiles:
    group:
      local:
        - jwt
        - mail
        - oauth
        - local
      prod:
        - prod
      active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


